### ISSUE TITLE
Any workspace member can do this very quickly directly in Slack

### ISSUE THREAD

**Issue by tbc** [robby-dermody/slack-bulkinviter#12]
In your README you may want to point folks to the best practice any Slack workspace member can do very quickly directly in Slack. See the Web Applications StackExchange: [How do I invite all team members to a new Slack channel?](https://j.mp/2SkuFKC)

I'm fine with you assigning this issue to me. I just can't make time for this little pull request today.

—tbc MIT VI-3 '84

**Comment by tdemarest** [comment]
This doesn't work when there are > 99 members to be invited. This is even mentioned in the comments in StackExchange. If this is included in the README definitely include this caveat. I'm in the process of making changes to the script to work with the new Slack API calls including pagination for very large conversations and members.

**Comment by tdemarest** [comment]
The /who method suffers from only returning 99 max users. There is an easier way that I tested today - use the "+ Add people" option from the UI in a channel. I successfully tested pasting over 2000 email addresses and it worked. It took more than 10 minutes but everyone was added.

I still plan on updating the script to use the official python-slackclient and the new API calls. I'm done just need to run a few more test scenarios with large number of lists and users with the new pagination options.

**Comment by tbc** [comment]
Ah, good catch. I work for a small org with < 100 workspace members. Sorry I missed that. Do you want me to work more on the README?

**Comment by tdemarest** [comment]
I'd definitely update your pull request. There are some other options that also work so there are multiple ways to bulk add users other than the script. I was going to comprehensively add them to my fork and create a pull request for the new version I'm finishing up.

**UPDATE**: I finished the rework for the official Slack Python client for the bulk invite script. It's still probably the best way for large teams with lots of users. I didn't update the `slack-bulkinviter-one-user-all-non-private-channels.py` script.
