### ISSUE TITLE
slacker.Error: ura_max_channels

### ISSUE THREAD

**Issue by neilrooney** [robby-dermody/slack-bulkinviter#8]
Currently getting this error and have not been able to solve it as of yet. Any ideas?

**Comment by realflash** [comment]
Me too. Got halfway through and died with this error. Dying on a different user each time without making further progress.

Relevant seems to be https://api.slack.com/methods/channels.invite

I'm thinking that it is single channel guests that are the problem.

**Comment by realflash** [comment]
There a number of different errors that can occur, for single channel guests, apps, bots, deactivated users etc. Those who have forked this code have already written fixes for these errors and added things like sleeps to avoid rate limiting problems. 

I switched to https://github.com/tdemarest/slack-bulkinviter and fixed the issue.
